name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the server Docker image
      run: docker build -t kunal31311/server ./server
    
    - name: Build Client Docker Image
      run: docker build -t kunal31311/client ./client



    - name:  Push Server Image
      run: docker push kunal31311/server:latest

    - name: Push Client Image
      run: docker push kunal31311/client:latest



